config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index'

  resources :contacts, only: [:index, :show, :new, :create]

  resources :companies do
    resources :jobs, except: [:show, :index]
    resources :contacts, only: [:create], to: "company/contacts#create"
  end


  resources :jobs, only: [:show, :index] do
    resources :comments, only: [:create]
  end
  resources :categories

  get '/dashboard' => 'calculations#dashboard', as: 'dashboard'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :title, presence: true
  validates :title, uniqueness: { case_sensitive: false }
  has_many :jobs
end

app/models/city.rb
class City < ActiveRecord::Base
  validates :name, presence: true
  validates :state, presence: true
  validates :name, uniqueness: true

  has_many :jobs, dependent: :destroy

  def jobs_count
    self.jobs.count
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :job, presence: true
  belongs_to :job

  def display_time
    created_at.strftime('%d %b %Y, %l:%M %p')
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :jobs
  has_many :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :company

  validates :name, presence: true

  def company_name
    company ? company.name : ""
  end
end

app/models/dashboard.rb
class Dashboard
  def top_three_companies_by_interest
    sorted = Company.all.sort_by do |company|
      company.average_interest
    end.reverse
    sorted[0..2]
  end

  def job_locations
    Job.locations
  end

  def job_count_by_location(location)
    Job.where(city: location).count
  end

  def job_interest_levels
    Job.interest_levels
  end

  def job_count_by_interest(interest_level)
    Job.where(level_of_interest: interest_level).count
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, :level_of_interest, :city, presence: true
  belongs_to :company
  has_many :job_tags
  has_many :tags, through: :job_tags

  def count_tags
    self.job_tags.count(:job_id)
  end

end

app/models/job_tag.rb
class JobTag < ActiveRecord::Base
  belongs_to :job
  belongs_to :tag
end

app/models/jobs_tag.rb
class JobsTag < ActiveRecord::Base
  belongs_to :job
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :job_tags
  has_many :jobs, through: :job_tags
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :job


end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true, uniqueness: true
end

app/controllers/job_helper.rb
module JobHelper

  def sort_by(attribute, list)
    if attribute.eql? "location"
      list.order(:city)
    elsif attribute.eql? "interest"
      list.order('level_of_interest DESC')
    elsif attribute.eql? "company"
      list.order(:company_id)
    else
      list
    end
  end

  def list
    if @location
      Job.where(city: @location)
    elsif @category
      @category.jobs
    else
      set_company.jobs
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/company_helper.rb
module CompanyHelper
  extend self

  def get_params(params)
    if params[:sort] == "location"
      companies = Company.sorted_companies
    elsif params[:location]
      companies = Company.where(city: params[:location])
    else
      companies = Company.all
    end
  end

  def search_params(params)
    if Company.find_by(name: params["search-id"]).nil?
      message = "Company does not exist"
      redirect_to errors_path
    else
      company = Company.find_by(name: params["search-id"])
      redirect_to company_path(company)
    end
  end

  def get_dashboard
    jobs = Job.job_count
    companies = Company.top_three_interests
    locations = Company.location_count

    [jobs, companies, locations]
  end

end

app/helpers/contact_helper.rb
module ContactHelper
  extend self

  def get_params(params, contact_params)
    contact = Contact.new(contact_params)
    contact.company_id = params[:company_id]
    company = contact.company

    [contact, company]
  end
end

app/helpers/job_helper.rb
module JobHelper
  extend self

  def get_params(params)
    company = Company.find(params[:company_id]) if params[:company_id]

    if params[:sort] == "interest"
      jobs = Job.all.order(level_of_interest: :desc)
    elsif params[:company_id].nil?
        jobs = Job.all
    else
      jobs = company.jobs
    end
    [company, jobs]
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
  def sort_jobs_by_interest?
    if params[:sort]
      @sorted_by_interest_note = "Sorted by level_of_interest:"
      @jobs = Job.all.sort_by_interest
      render :sorted_index
    else
      @company = Company.find(params[:company_id])
      @jobs = @company.jobs
    end
  end

  def create_helper
    if @job.save
      flash[:success] = "You created #{@job.title} at #{@company.name}"
      redirect_to company_job_path(@company, @job)
    else
      render :new
    end
  end

  def update_helper
    if @job.save
      redirect_to company_jobs_path(@job.company, @job)
    else
      render :edit
    end
  end

  def category_helper
    @job.category.nil? ? 'not assigned' : @job.category.title
  end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/shared/_default_navbar.html.erb
<div id="sources" role="navigation">
  <div class='col-md-12 navbar navbar-default navbar-fixed-top'>
    <a href='/' class='navbar-brand'>Job Tracker</a>
    <ul class='nav navbar-nav navbar-right'>

      <li class='dropwdown'>
        <a href = '#' class='dropdown-toggle' data-toggle='dropdown'>Create New
          <span class="caret"></span></a>
          <ul class='dropdown-menu'>
            <li><%= link_to "New Company", new_company_path %></li>
            <li><%= link_to "New Category", new_category_path %></li>
            <li><%= link_to "New Tag", new_tag_path %></li>
          </ul>
        </li>

      <li class='dropwdown'>
        <a href = '#' class='dropdown-toggle' data-toggle='dropdown'>View All
          <span class="caret"></span></a>
          <ul class='dropdown-menu'>
            <li><%= link_to "All Companies", companies_path(sort: "location") %></li>
            <li><%= link_to "All Jobs", jobs_path(sort: "interest") %></li>
            <li><%= link_to "All Categories", categories_path %></li>
            <li><%= link_to "All Tags", tags_path %></li>
          </ul>
        </li>

    </ul>
    <form class="navbar-form" role="search" action="/redirect" method="get">
			<div class="input-group">
				<input type="text" class="form-control" placeholder="Search Company" name="search-id">
				<span class="input-group-btn">
					<button type="submit" class="btn btn-default" value="Submit">
						<span class="glyphicon glyphicon-search">
							<span class="sr-only">Search</span>
						</span>
					</button>
				</span>
			</div>
		</form>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if @errors %>
  <div class="alert alert-danger">
    <h3><%= pluralize(@errors.count, 'error') %> prevented this record from being saved</h3>
    <ul>
      <% @errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="container">
    <div class="alert alert-success">
        <%= content_tag :div, msg, class: name %>
    </div>
  </div>
<% end %>
  

app/views/shared/_nav.html.erb
<nav role="navigation">
  <ul class="nav nav-tabs">
    <li role="presentation"><%= link_to "Dashboard", dashboard_path %></li>
    <li role="presentation"><%= link_to "Companies", companies_path %></li>
    <li role="presentation"><%= link_to "Contacts", contacts_path %></li>
    <li role="presentation"><%= link_to "Categories", categories_path %></li>
    <li role="presentation"><%= link_to "Jobs", jobs_path %></li>
  </ul>
</nav>

app/views/shared/_notices.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>">
    <%= content_tag :div, msg, class: name %>
  </div>
<% end %>

app/views/shared/dashboard.html.erb
<div class="container">
  <h1>Job Tracker Dashboard</h1>
</div>

<div class="container">
  <div class="col-md-6">
    <h3>Top <%= @top_companies.count%> Companies by Level of Interest</h3>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Rank</th>
          <th>Average Level of Interest</th>
          <th>Company</th>
        </tr>
      </thead>

      <tbody>
        <% @top_companies.each_with_index do |company, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= company.average_level_of_interest %></td>
          <td><%= link_to company.name, company_path(company)%></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="container">

  <div class="col-md-6">
    <h3>Number of Jobs by Level of Interest</h3>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Level of Interest</th>
          <th>Job Count</th>
        </tr>
      </thead>

      <tbody>
        <% @job_count_by_interest.each do |level, count| %>
        <tr>
          <td><%= level %></td>
          <td><%= count %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
    

  <div class="col-md-6">
    <h3>Number of Jobs by Location</h3>

    <table class="table table-hover">
      <thead>
        <tr>
          <th>City</th>
          <th>Job Count</th>
        </tr>
      </thead>

      <tbody>
        <% @job_count_by_location.each do |location, count| %>
        <tr>
          <td><%= link_to location, jobs_path(:location => location) %></td>
          <td><%= count %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>