config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index'

  resources :contacts, only: [:index, :show, :new, :create]

  resources :companies do
    resources :jobs, except: [:show, :index]
    resources :contacts, only: [:create], to: "company/contacts#create"
  end


  resources :jobs, only: [:show, :index] do
    resources :comments, only: [:create]
  end
  resources :categories

  get '/dashboard' => 'calculations#dashboard', as: 'dashboard'

end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :jobs
  has_many :contacts

end

app/controllers/companies/jobs_controller.rb
class Companies::JobsController < ApplicationController
  def index
    @company = Company.find(params[:company_id])
    @jobs = Job.all
    @contacts = @company.contacts
    @contact = Contact.new()
  end

  def new
    @company = Company.find(params[:company_id])
    @jobs = @company.jobs
    @job = Job.new()
    @categories = Category.all
  end

  def create
    @company = Company.find(params[:company_id])
    @job = @company.jobs.new(job_params)
    if @job.save
      flash[:success] = "You created #{@job.title} at #{@company.name}"
      redirect_to company_job_path(@company, @job)
    else
      render :new
    end
  end

  def show
    @company = Company.find(params[:company_id])
    @job = Job.find(params[:id])
    @comment = Comment.new()
    @comment.job_id = @job.id
  end

  def edit
    @company = Company.find(params[:company_id])
    @job = Job.find(params[:id])
    @categories = Category.all
  end

  def update
    @company = Company.find(params[:company_id])
    @job = Job.find(params[:id])
    @job.update(job_params)
    if @job.save
      flash[:success] = "#{@job.title} updated!"
      redirect_to company_job_path(@company, @job)
    else
      render :edit
    end
  end

  def destroy
    job = Job.find(params[:id])
    job.delete
    flash[:success] = "#{job.title} was successfully deleted!"

    @company = Company.find(params[:company_id])
    redirect_to company_jobs_path(@company)
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :level_of_interest, :city, :category_id)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:success] = "Company, #{@company.name}, was successfully created!"
      redirect_to company_path(@company)
    else
      @errors = @company.errors
      render :new
    end
  end

  def show
    @company = find_company(params[:id])
    @jobs = @company.jobs
    @contact = Contact.new
  end

  def edit
    @company = find_company(params[:id])
  end

  def update
    @company = find_company(params[:id])
    @company.update(company_params)
    if @company.save
      flash[:success] = "#{@company.name} updated!"
      redirect_to company_path(@company)
    else
      @errors = @company.errors
      render :edit
    end
  end

  def destroy
    company = find_company(params[:id])
    company.jobs.destroy_all
    company.delete

    flash[:success] = "#{company.name} and all associated jobs for #{company.name} were successfully deleted!"
    redirect_to companies_path
  end


  private

  def company_params
    params.require(:company).permit(:name, :city)
  end
end

app/controllers/company/contacts_controller.rb
class Company::ContactsController < ApplicationController

  def create
    @company = find_company(params[:company_id]) if params[:company_id]
    contact = @company.contacts.new(contacts_params)
    if contact.save
      flash[:success] = "#{contact.name} was added as a contact to #{@company.name}"
      redirect_to company_path(@company)
    else
      flash[:danger] = "Contact must have a Name and Email to be valid."
      redirect_to company_path(@company)
    end
  end

  private

  def contacts_params
    params.require(:contact).permit(:name, :email, :position)
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
  def sort_companies_by_city?
    if params[:sort]
      @sorted_by_city_note = "Sorted by city alphabetic order:"
      @companies = Company.all.sort_by_city
    else
      @companies = Company.all
    end
  end

  def display_only_one_location?
    if params[:location]
      @sorted_by_city_note = "Jobs in this city:"
      @companies = Company.where(city: params[:location])
    else
      @companies = Company.all
    end
  end

  def create_helper
    if @company.save
      flash[:success] = "#{@company.name} added!"
      redirect_to company_path(@company)
    else
      render :new
    end
  end

  def update_helper
    if @company.save
      flash[:success] = "#{@company.name} updated!"
      redirect_to company_path(@company)
    else
      render :edit
    end
  end
end

app/helpers/company_helper.rb
module CompanyHelper
  extend self

  def get_params(params)
    if params[:sort] == "location"
      companies = Company.sorted_companies
    elsif params[:location]
      companies = Company.where(city: params[:location])
    else
      companies = Company.all
    end
  end

  def search_params(params)
    if Company.find_by(name: params["search-id"]).nil?
      message = "Company does not exist"
      redirect_to errors_path
    else
      company = Company.find_by(name: params["search-id"])
      redirect_to company_path(company)
    end
  end

  def get_dashboard
    jobs = Job.job_count
    companies = Company.top_three_interests
    locations = Company.location_count

    [jobs, companies, locations]
  end

end

app/views/companies/_contact.html.erb
<div class="list-group">
  <div class="list-group-item">
    <h4 class="list-group-item-heading"><%= contact.name %></h4>
    <p class="list-group-item-text"><%= contact.email %></p>
    <p class="list-group-item-text"><%= contact.position %></p>
  </div>
</div>

app/views/companies/_contact_form.html.erb
<%= form_for [@company, @contact], :html => {:class => "form-horizontal"} do |f| %>
  <div class = "form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class = "col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>

  <div class = "form-group">
    <%= f.label :position, :class => "col-sm-2 control-label" %>
    <div class = "col-sm-10">
      <%= f.text_field :position, :class => "form-control" %>
    </div>
  </div>

  <div class = "form-group">
    <%= f.label :email, :class => "col-sm-2 control-label" %>
    <div class = "col-sm-10">
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div>

  <div class = "form-group">
    <div class = "col-sm-offset-2 col-sm-10">
      <%= f.submit @form[:submit_contact], :class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/companies/_contacts.html.erb
<h4> All Contacts for <%= @companies.name %> <br>
<table>
  <thead>
    <tr>
      <th><weak> Name <weak></th>
      <th> Position </th>
      <th> Email </th>
    </tr>
  </thead>
  <tbody>
    <% @company.contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.position %></td>
        <td><%= contact.email %></td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/companies/_form.html.erb
<%= bootstrap_form_for @company do |f| %>

  <%= f.text_field :name, hide_label: true, placeholder: "Name" %>

  <%= f.submit %>
<% end %>

app/views/companies/_header.html.erb
<h1><%= @header[:title] %>
  <% if @header[:show_name]%>
    <span class="label label-default header-highlight">
      <%= @company.name %>
    </span>
  <% end %>
  <% if @header[:show_add]%>
    <%= link_to "Add Company", new_company_path, class: "btn btn-default" %>
  <% end %>
  <% if @header[:show_edit]%>
    <%= link_to "Edit Company Details", edit_company_path(@company), class: "btn btn-warning" %>
  <% end %>
  <% if @header[:show_delete]%>
    <%= link_to "Delete Company", company_path(@company), method: :delete, class: "btn btn-danger" %>
  <% end %>
</h1>

<% if @header[:show_index]%>
  <p><%= link_to "Back to Company List", companies_path, class: "btn btn-primary btn-xs" %></p>
<% end %>

app/views/companies/companies_by_location.html.erb
<ol class="breadcrumb">
  <li>
    <a href="/companies">Companies</a>
  </li>
  <li class="active">Companies in <%= @city %> </li>
</ol>


<h1>Companies in <%= @city %></h1>
<ul>
  <% @companies_by_location.each do |company| %>
    <li>
      <%= link_to company.name, company_path(company) %>
    </li>
  <% end %>
</ul>

app/views/companies/dashboard.html.erb
<h1>Job Tracker Dashboard</h1>
<hr>
<div class="row">
  <div class="col-md-4 top-three">
    <h2>Top Three Companies by Average Level of Interest</h2>
    <br>
    <ul class="list-group">
      <% @top_three_companies.each do |company_hash| %>
        <li class="list-group-item">
          <span class="badge"><%= company_hash.values.first %></span>
          <%= link_to company_hash.keys.first.name, company_jobs_path(company_hash.keys.first) %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="col-md-4 level_of_interest">
    <h2>Number of Jobs at Level of Interest</h2>
    <br>
    <ul class="list-group">
      <% @jobs_by_level_of_interest.keys.each do |level| %>
        <li class="list-group-item">
          <span class="badge"><%= @jobs_by_level_of_interest[level] %></span>
          <%= level %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="col-md-4 location">
    <h2>Number of Jobs at Location</h2>
    <br>
    <ul class="list-group">
      <% @jobs_by_location.keys.each do |city| %>
        <li class="list-group-item">
          <span class="badge"><%= @jobs_by_location[city] %></span>
          <%= link_to city, "/jobs?location=#{city}" %>
        </li>
      <% end %>
    </ul>
  </div>


</div>

app/views/companies/edit.html.erb
<h2>Edit <%= @company.name %></h2>

<%= render partial: "form" %>

app/views/companies/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Company</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @companies.each do |company| %>
      <tr class=company_<%= company.id %>>
        <td>
          <%= link_to company.name, company_path(company), class: "table_name" %>
        </td>
        <td>
          <%= link_to "Edit", edit_company_path(company) %>
          <%= link_to "Delete",
            company_path(company),
            method: :delete,
            data: {confirm: "Are you sure you would like to delete #{company.name} and ALL of its asociated jobs?"}
          %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Add a new company", new_company_path %>

app/views/companies/new.html.erb
<h2>Create a new company</h2>

<%= render partial: "form" %>

app/views/companies/show.html.erb
<h2><strong><%= @company.name %></strong></h2>

<h3>All jobs</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>City</th>
      <th>Level of Interest</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr class="job_<%= job.id %>">
        <td>
          <%= link_to job.title, job_path(job), class: "table_name" %>
        </td>
        <td>
          <%= link_to job.category_title, category_path(job.category), class: "table_name" %>
        </td>
        <td><%= job.city %></td>
        <td><%= job.level_of_interest %></td>
        <td><%= link_to "Edit", edit_company_job_path(@company, job) %></td>
        <td><%= link_to "Delete", company_job_path(@company, job),
          method: :delete,
          data: {confirm: "Are you sure you would like to delete the job, #{job.title}, in #{job.city}?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Add a new job", new_company_job_path(@company) %>

<h3>Add information for a contact at <%= @company.name %></h3>
<%= render partial: 'contacts/form' %>


<% if @company.contacts.any? %>
  <h3><strong>Contacts</strong></h3>
  <div class="list=group">
    <%= render partial: 'companies/contact', collection: @company.contacts.reverse %>
  </div>
<% end %>