config/routes.rb
Rails.application.routes.draw do

  root 'jobs#index'

  resources :contacts, only: [:index, :show, :new, :create]

  resources :companies do
    resources :jobs, except: [:show, :index]
    resources :contacts, only: [:create], to: "company/contacts#create"
  end


  resources :jobs, only: [:show, :index] do
    resources :comments, only: [:create]
  end
  resources :categories

  get '/dashboard' => 'calculations#dashboard', as: 'dashboard'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :title, presence: true
  validates :title, uniqueness: { case_sensitive: false }
  has_many :jobs
end

app/models/city.rb
class City < ActiveRecord::Base
  validates :name, presence: true
  validates :state, presence: true
  validates :name, uniqueness: true

  has_many :jobs, dependent: :destroy

  def jobs_count
    self.jobs.count
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :job, presence: true
  belongs_to :job

  def display_time
    created_at.strftime('%d %b %Y, %l:%M %p')
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :jobs
  has_many :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :company

  validates :name, presence: true

  def company_name
    company ? company.name : ""
  end
end

app/models/dashboard.rb
class Dashboard
  def top_three_companies_by_interest
    sorted = Company.all.sort_by do |company|
      company.average_interest
    end.reverse
    sorted[0..2]
  end

  def job_locations
    Job.locations
  end

  def job_count_by_location(location)
    Job.where(city: location).count
  end

  def job_interest_levels
    Job.interest_levels
  end

  def job_count_by_interest(interest_level)
    Job.where(level_of_interest: interest_level).count
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, :level_of_interest, :city, presence: true
  belongs_to :company
  has_many :job_tags
  has_many :tags, through: :job_tags

  def count_tags
    self.job_tags.count(:job_id)
  end

end

app/models/job_tag.rb
class JobTag < ActiveRecord::Base
  belongs_to :job
  belongs_to :tag
end

app/models/jobs_tag.rb
class JobsTag < ActiveRecord::Base
  belongs_to :job
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :job_tags
  has_many :jobs, through: :job_tags
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :job


end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true, uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
    @category = Category.new
  end

  def index
    @categories = Category.all
  end

  def show
    @category = find_category(params[:id])
    @jobs = @category.jobs
  end

  def edit
    @category = find_category(params[:id])
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category, #{@category.title}, was successfully created!"
      redirect_to category_path(@category)
    else
      @errors = @category.errors
      render :new
    end
  end

  def update
    @category = find_category(params[:id])
    if @category.update(category_params)
      redirect_to category_path(@category)
    else
      @errors = @category.errors
      render :edit
    end
  end

  def destroy
    category = find_category(params[:id])
    category.jobs.destroy_all
    category.delete
    flash[:success] = "#{category.title} and all associated jobs for #{category.title} were successfully deleted!"
    redirect_to categories_path
  end

  private

    def category_params
      params.require(:category).permit(:title)
    end

    def find_category(id)
      Category.find(id)
    end
end

app/controllers/job_helper.rb
module JobHelper

  def sort_by(attribute, list)
    if attribute.eql? "location"
      list.order(:city)
    elsif attribute.eql? "interest"
      list.order('level_of_interest DESC')
    elsif attribute.eql? "company"
      list.order(:company_id)
    else
      list
    end
  end

  def list
    if @location
      Job.where(city: @location)
    elsif @category
      @category.jobs
    else
      set_company.jobs
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/company_helper.rb
module CompanyHelper
  extend self

  def get_params(params)
    if params[:sort] == "location"
      companies = Company.sorted_companies
    elsif params[:location]
      companies = Company.where(city: params[:location])
    else
      companies = Company.all
    end
  end

  def search_params(params)
    if Company.find_by(name: params["search-id"]).nil?
      message = "Company does not exist"
      redirect_to errors_path
    else
      company = Company.find_by(name: params["search-id"])
      redirect_to company_path(company)
    end
  end

  def get_dashboard
    jobs = Job.job_count
    companies = Company.top_three_interests
    locations = Company.location_count

    [jobs, companies, locations]
  end

end

app/helpers/contact_helper.rb
module ContactHelper
  extend self

  def get_params(params, contact_params)
    contact = Contact.new(contact_params)
    contact.company_id = params[:company_id]
    company = contact.company

    [contact, company]
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/job_helper.rb
module JobHelper
  extend self

  def get_params(params)
    company = Company.find(params[:company_id]) if params[:company_id]

    if params[:sort] == "interest"
      jobs = Job.all.order(level_of_interest: :desc)
    elsif params[:company_id].nil?
        jobs = Job.all
    else
      jobs = company.jobs
    end
    [company, jobs]
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
  def sort_jobs_by_interest?
    if params[:sort]
      @sorted_by_interest_note = "Sorted by level_of_interest:"
      @jobs = Job.all.sort_by_interest
      render :sorted_index
    else
      @company = Company.find(params[:company_id])
      @jobs = @company.jobs
    end
  end

  def create_helper
    if @job.save
      flash[:success] = "You created #{@job.title} at #{@company.name}"
      redirect_to company_job_path(@company, @job)
    else
      render :new
    end
  end

  def update_helper
    if @job.save
      redirect_to company_jobs_path(@job.company, @job)
    else
      render :edit
    end
  end

  def category_helper
    @job.category.nil? ? 'not assigned' : @job.category.title
  end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/categories/_form.html.erb
<%= bootstrap_form_for @category do |f| %>
  <%= f.text_field :title, hide_label: true, placeholder: "Title" %>

  <%= f.submit %>
<% end %>

app/views/categories/_header.html.erb
<h1><%= @header[:title] %>
  <% if @header[:show_name]%>
    <span class="label label-default header-highlight">
      <%= @category.title %>
    </span>
  <% end %>
  <% if @header[:show_add]%>
    <%= link_to "Add Category", new_category_path, class: "btn btn-default" %>
  <% end %>
  <% if @header[:show_edit]%>
    <%= link_to "Edit Category Details", edit_category_path(@category), class: "btn btn-warning" %>
  <% end %>
  <% if @header[:show_delete]%>
    <%= link_to "Delete Category", category_path(@category), method: :delete, class: "btn btn-danger" %>
  <% end %>
</h1>

<% if @header[:show_index]%>
  <p><%= link_to "Back to Category List", categories_path, class: "btn btn-primary btn-xs" %></p>
<% end %>

app/views/categories/edit.html.erb
<h2>Edit <%= @category.title %></h2>

<%= render partial: 'form' %>

app/views/categories/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Category</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr class=category_<%= category.id %>>
        <td>
          <%= link_to category.title, category_path(category), class: "table_name" %>
        </td>
        <td>
          <%= link_to 'Edit', edit_category_path(category) %>
          <%= link_to 'Delete',
            category_path(category),
            method: :delete,
            data: {confirm: "Are you sure you would like to delete #{category.title} and ALL of its associated jobs?"}
          %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Add a new category", new_category_path %>

app/views/categories/new.html.erb
<h2>Create a new category</h2>

<%= render partial: 'form' %>

app/views/categories/show.html.erb
<h2>All Jobs for <strong><%= @category.title %></strong></h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Company</th>
      <th>City</th>
      <th>Level of Interest</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr class="job_<%= job.id %>">
        <td>
          <%= link_to job.title, job_path(job), class: "table_name" %>
        </td>
        <td>
          <%= link_to job.company_name, company_path(job.company), class: "table_name" %>
        </td>
        <td><%= job.city %></td>
        <td><%= job.level_of_interest %></td>
        <td><%= link_to "Edit", edit_company_job_path(job.company, job) %></td>
        <td><%= link_to "Delete", job_path(job),
          method: :delete,
          data: {confirm: "Are you sure you would like to delete the job, #{job.title}, in #{job.city}?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>